### ISSUE TITLE
Running the project on Ubuntu 18.10 fails with ZipException

### ISSUE THREAD

**Issue by mvysny** [alejandro-du/embedded-jetty-demo#1]
Running the project, both `Application.main` from Intellij, and `java -jar target/embedded-jetty-demo-1.0-SNAPSHOT.jar` from command-line, on `openjdk-8-jdk` fails with:

```
java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:103)
        at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
        at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)
        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
        at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.getTlds(MetaInfConfiguration.java:438)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanForTlds(MetaInfConfiguration.java:355)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanJars(MetaInfConfiguration.java:173)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:102)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:506)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:544)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.server.Server.start(Server.java:415)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:382)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at com.example.Application.run(Application.java:45)
        at com.example.Application.main(Application.java:17)
```
The problematic file is `libatk-wrapper.so` which is definitely not a jar/zip file, but Jetty tries to open it anyway.

**Comment by mvysny** [comment]
Changing the line in `Application.java` to
```
context.setAttribute("org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern", ".*.jar|.*/classes/.*");
```
helped.

**Comment by mcsherrylabs** [comment]
@mvysny "You are ..... so beautiful ..... to me......., YOU are SO beautiful .... toooo meeeeeeeeee!".
Ahem, thanks a lot. I had narrowed it down to this line but nothing I replaced it with worked....
